#!/bin/bash
# countWords word file
#  Prints the number of times word occurs in file

usage() {
	echo "${0} word file"
	exit 1
}

# Do we have exactly 2 command-line arguments or not?
if [ $# -ne 2 ]; then
	usage
fi

counter=0  # Initialize the counter to 0.

#Iterate over every word in the file, ${2}.
for word in $(cat "${2}"); do
  if [ ${word} == "${1}" ]; then
    counter=$((counter + 1))
  fi
done
echo ${counter}
